"""add project_members and activity_log

Revision ID: 05befa31187d
Revises: 9e78d8cb8367
Create Date: 2026-02-18 17:51:23.074559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05befa31187d'
down_revision: Union[str, Sequence[str], None] = '9e78d8cb8367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='unique_project_member')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('created_by', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'user_id')
    op.add_column('prompts', sa.Column('created_by', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('prompts_user_id_fkey'), 'prompts', type_='foreignkey')
    op.create_foreign_key(None, 'prompts', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('prompts', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.create_foreign_key(op.f('prompts_user_id_fkey'), 'prompts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('prompts', 'created_by')
    op.add_column('projects', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'created_by')
    op.drop_table('activity_log')
    op.drop_table('project_members')
    # ### end Alembic commands ###
